### ISSUE TITLE
two minor issues

### ISSUE THREAD

**Issue by metasong** [orange-games/phaser-input#14]
when using nodejs + typescript + webpack, and in ts file:
import * as Fabrique from 'phaser-input/build/phaser-input'; 
when compile warnings and errors occurs:
solution:
1. add export = Fabrique; to   phaser-input.d.ts
2. copy the ts folder to the phaser-input folder that installed in node-modules folder

**Comment by AleBles** [comment]
Please check the following for using this library with webpack: https://github.com/orange-games/phaser-input/issues/7

Last comment should work for you
