### ISSUE TITLE
Input DOM visiible in Firefox

### ISSUE THREAD

**Issue by Alaxe** [orange-games/phaser-input#28]
When I ran my [game](https://github.com/Alaxe/gemini) in Firefox I could see the DOM element used for the input in the upper left corner. I looked at the computed box model in the developer console and there was a border of `8px`. I fixed it with simple CSS:
```
input {
    border: 0px;
}
```
I am not very experienced with HTML / CSS so I am not sure if a similar solution would fix the problem in all browsers and that it wouldn't introduce new ones. If you think it would be fine I can patch it and submit a PR (it's a few lines of code [here](https://github.com/orange-games/phaser-input/blob/master/ts/InputElement.ts#L31)). Also I would set padding to 0px as well just to be on the safe side.

### Some technical details:
**OS**: Arch Linux
**Firefox Version**:  50.1.0 (should be the latest)
**Plugin Version**: 1.2.6 (from NPM) I am not using the latest version from the repo, but after a quick look at the source the issue doesn't seem to have been addressed.

I hope I haven't missed anything. I'd be happy to help you in any way I can. 
Thanks for your time and attention.

**Comment by AleBles** [comment]
Thanks for reporting! :)

**Comment by Alaxe** [comment]
I'm glad to have helped  :)
