### ISSUE TITLE
z-index not working

### ISSUE THREAD

**Issue by EricMatthews1993** [orange-games/phaser-input#29]
First, thank you for this great input box! I altered it a little bit to allow submitting to a callback upon pressing enter.

Anyway, I am trying to set the z-index of the component, but am having no effect. The text box goes over most of my game sprites, except for text that I have at a specific z-index.

How can I make sure that the text box is above everything?

Thank you

**Comment by AleBles** [comment]
it kinda depends on what you mean. We have a html input field which is offset in such a way that it doesn't appear on screen. You can set the z-index on this element but it indeed won't have any effect.

Then there is also the InputField object which behaves like a Phaser.Sprite, so you should be able to put it on top with the build-in phaser methods: [bringToTop](http://phaser.io/docs/2.4.4/Phaser.World.html#bringToTop).

And as with other Sprites, the order of appearance equals the order of adding them to the stage.
