### ISSUE TITLE
Enter or Return toggles input focus

### ISSUE THREAD

**Issue by EddieOne** [orange-games/phaser-input#3]
I have a different use case where the input is reused for chat or command input. I got this to work but it was fiddly. Here's how.

remove the following from phaser-input.js (probably should be up to the app anyways)
```
if (evt.keyCode === 13) {
    this.endFocus();
    return;
}
```

Here I am using WASD for movement, so disabling that is needed during chat input.

```
this.startInput = function() {
	game.game.input.enabled = false;
	this.chatInput.startFocus();
	this.chatInput.focus = true;
	this.chatInput.placeHolder.visible = false;
};
	
this.stopInput = function() {
	this.chatInput.endFocus();
	this.chatInput.focus = false;
	game.game.input.enabled = true;
};
```

Finally, I get the value when the enter key is pressed and clear the input using resetText()

**Comment by AleBles** [comment]
So If I understand correctly, there are things you'd like to see changed:
1) Don't capture enter in the library (makes sense, i'll make it an optional piece)
2) Disable input in the game all together when inputting text (completely makes sense, consider it done)

**Comment by EddieOne** [comment]
I wasn't sure if I should make a pull or not. I figured I would at least share my experience.

1. I agree with.
2. Sure didn't think of that

Also, I was thinking it would be nice if there was a manual start and stop, so devs could bind them to what ever keys they want. Otherwise, updating the readme could also go a long way.

ps. thanks for sharing. I updated my answer here http://stackoverflow.com/questions/32071579/how-to-take-text-input-in-phaser

**Comment by AleBles** [comment]
I think I mis understood your second code example then, but I get it now. And with manual start/stop, do you mean when to focus and/or focus out on the input field? This shouldn't be so hard, but I think this might cause issues for mobile focusing, as Safari and Chrome mobile are pretty picky on how to achieve this. It's only allowed by a touch event.

Still I could make those bind/call-able

**Comment by EddieOne** [comment]
Oh I see. I haven't been able to test on mobile yet. Yeah, it wasn't clear how to manually focus and blur. The above code works for desktop Chrome. I still need to test other browsers.

**Comment by AleBles** [comment]
Okay so:

* startFocus / endFoucs are made public
* capture enter is optional with focusOutOnEnter property (defaults to true)
* Input in phaser when inputField is active can be blocked with blockInput property (defaults to true)

Are your issues here resolved? :)

**Comment by EddieOne** [comment]
That sounds great. Thanks for making those changes.
