### ISSUE TITLE
Set input value

### ISSUE THREAD

**Issue by roskhill** [orange-games/phaser-input#38]
This is not necessarily an issue but, just wasn't sure where else to raise it.

In CanvasInput you can set a value for the field, is this something you can achieve with phaser-input?

So when a text input field is created it is automatically populated with an existing value ( If one exists ).  Is this something that can be achieved using JavaScript alone if the ability is unavailable in phaser-input?

**Comment by AleBles** [comment]
You can use inputField.setText() :)

**Comment by roskhill** [comment]
Thanks, can see it has been added to the documentation now as well
