### ISSUE TITLE
No cursor when added as child

### ISSUE THREAD

**Issue by korroktheslavemaster** [orange-games/phaser-input#4]
When I add the inputField as a child to a sprite, the blinking cursor stops showing. Everything else working as expected.

**Comment by AleBles** [comment]
The cursor is updated within Phaser's update loop, this calls the update function for all Phaser objects in the tree. By using addChild() you are going into PIXI territory and you loose the ability for using update(). You can manually resolve this by calling update() yourself on the InputField object.

**Comment by korroktheslavemaster** [comment]
Thanks for the reply, I've used InputField a lot. Could you please make it more clear in the readme how to add event handlers?

**Comment by AleBles** [comment]
Sure, You mean the keyboard open/close signals?

**Comment by korroktheslavemaster** [comment]
I mean callbacks for key presses. Also (as pointed out in another answer) a way to not have the enter key toggle keyboard.
