### ISSUE TITLE
Multiple inputs will all have content width as the last created input

### ISSUE THREAD

**Issue by squilibob** [orange-games/phaser-input#5]
I created several inputs of varying widths, the last being a small width. All the inputs would then cut off the inputted text at the width of that small width input. If any input is larger in width than the last created input then it will be cut off at that width of the last created input.

**Comment by AleBles** [comment]
Good find! I'll have a look soon

**Comment by squilibob** [comment]
I have traced this problem back to type breaking the widths if it is assigned an unexpected value. I think you should validate type just in case.
