### ISSUE TITLE
What are the accepted values for font weight?

### ISSUE THREAD

**Issue by ButsAndCats** [orange-games/phaser-input#60]
I have tried:

 - 'medium'
 - 'regular'
 - 'Medium'
 - 400
 - '400'

None of them seem to make any difference.

**Comment by AleBles** [comment]
Our InputOptions inherit from Phaser's so any CSS weight should work, it default's to normal (400) tho. But as per the [example](https://github.com/orange-games/phaser-input/blob/master/example/index.html) it should work. I'd like to point out that regular is not a valid option and 400 (normal) annd medium (500) are fairly similar, however (depending on the font used) they should show a little difference.

See Common weight name mapping @ https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

**Comment by ButsAndCats** [comment]
Perfect, thank you!
Might be handy to add to the readme for properties

**Comment by smartsingam** [comment]
Can you help me for phaser development.. I am new in phaser development can help me basic

**Comment by smartsingam** [comment]
Can you help me for phaser development.. I am new in phaser development can help me basic contact mail Id singaraj671@gmail.com
