### ISSUE TITLE
Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas) phaser

### ISSUE THREAD

**Issue by kenshero** [orange-games/phaser-input#64]
in phaser 2.3.0 have error like this.

it work if i use phaser v2.6 + but i want to use v2.3.0 because i have some bug about velocity in version 2.6 +

can you help me ?

![issue-phaser](https://user-images.githubusercontent.com/8245757/34074869-e2c22d1c-e2ea-11e7-814e-eabb05150f84.png)

**Comment by AleBles** [comment]
I know it's annoying but with Phaser v3 comming up I have no intention of making this work with v2.3. I happily accept working pull request tho
