### ISSUE TITLE
Setting text of unselected inputs

### ISSUE THREAD

**Issue by EddieOne** [orange-games/phaser-input#8]
Another use case where I'm putting x and y values in text inputs for a in-game map editor.

![map-editor](https://cloud.githubusercontent.com/assets/1835156/17187561/062d9f36-53f7-11e6-9b7b-997c51b18134.png)

Phaser Input expects the text field to be selected and have a place holder. The following changing let me do what I want but not the best code. More of a workaround.

```
InputField.prototype.setText = function (text) {
    if (text === void 0) { text = ''; }
        if (this.placeHolder) {
            if (text.length > 0) {
                this.placeHolder.visible = false;
            }
            else {
                this.placeHolder.visible = true;
               }
            }
            this.value = text;
            this.domElement.value = this.value;
            this.updateText();
                try {
                    this.updateCursor();
                } catch(e) {}
            this.endFocus();
        };
```

This is a little trick I use to update a sprite via the inputs without events. This is outside the scope of this issue but interesting nonetheless.

```
this.update = function() {
	if (this.xInput.focus) {
		this.selectedItem.x = this.xInput.value;
	}
	if (this.yInput.focus) {
		this.selectedItem.y = this.yInput.value;
	}
}
```

**Comment by AleBles** [comment]
Fixed the crashing, and nice to see your trick there!

**Comment by EddieOne** [comment]
Awesome thanks!
